language: node_js
node_js:
  - 12.16.1
before_install:
  - git clone https://github.com/jeffreyfei/md-notebook-gen.git ~/md-notebook-gen
  - git clone https://$GITHUB_USER:$GITHUB_TOKEN@github.com/noteshare/noteshare.github.io.git ~/website

script:
  - ./.deploy.sh
